Project Flask 2024/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Patient(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    patient_name = db.Column(db.String(128))
    allergy = db.Column(db.String(128))
    contact = db.Column(db.String(128))
    meds = db.Column(db.String(128))
    date = db.Column(db.DateTime(timezone = True), default = func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    added_by = db.Column(db.String(128))
    is_emergency = db.Column(db.Boolean)
    additional_notes = db.Column(db.String(1024))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(128), unique = True)
    password = db.Column(db.String(128))
    first_name = db.Column(db.String(128))
    patients = db.relationship('Patient')    

Project Flask 2024/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from flask_mail import Mail
from dotenv import load_dotenv
import os

load_dotenv()

db = SQLAlchemy()
DB_NAME = "database.db"
mail = Mail()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'place your secret-key here!' 
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SESSION_TYPE'] = 'filesystem'
    
    app.config['MAIL_SERVER'] = os.getenv('MAIL_SERVER')
    app.config['MAIL_PORT'] = int(os.getenv('MAIL_PORT'))
    app.config['MAIL_USE_TLS'] = os.getenv('MAIL_USE_TLS').lower() == 'true'
    app.config['MAIL_USE_SSL'] = os.getenv('MAIL_USE_SSL').lower() == 'true'
    app.config['MAIL_USERNAME'] = os.getenv('MAIL_USERNAME')
    app.config['MAIL_PASSWORD'] = os.getenv('MAIL_PASSWORD')
    app.config['MAIL_DEFAULT_SENDER'] = os.getenv('MAIL_DEFAULT_SENDER')

    mail.init_app(app)
    db.init_app(app)

    

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Patient

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

Project Flask 2024/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully', category = 'success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorect password', category = 'error')
        else:
            flash('Email does not exist', category = 'error')

    return render_template("login.html", user = current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exist', category = 'error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters', category = 'error')
        elif len(first_name) < 2:
            flash('First name must be greater than 2 characters', category = 'error')
        elif password1 != password2:
            flash('Passwords do not match', category = 'error')
        elif len(password1) < 8:
            flash('Password must be at least 8 characters', category = 'error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created', category='success')
            return redirect(url_for('views.home'))


    return render_template("sign_up.html", user = current_user)

Project Flask 2024/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, current_app, session, redirect, url_for
from flask_login import login_required, current_user
from . import db
from .models import Patient
from sqlalchemy.exc import SQLAlchemyError
import json
from .filters import get_added_by_options

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    added_by_options = get_added_by_options()
    selected_added_by = request.args.get('selected_added_by', '')

    if request.method == 'POST':
         
        patientName = request.form.get('patient_name')
        allergy = request.form.get('allergy')
        contact = request.form.get('contact')
        meds = request.form.get('meds')
        additional_notes = request.form.get('additional_notes')

        if len(patientName) < 3:
            flash('Patient name is too short!', category = 'error')
        if len(contact)<3:
            flash('Contact number too short!', category = 'error')
        else:
            meds = meds if meds else 'No meds provided'
            allergy = allergy if allergy else 'No allergy provided'
            additional_notes = additional_notes if additional_notes else 'No additional notes provided'
            new_patient = Patient(patient_name=patientName, allergy=allergy, contact=contact, meds=meds, is_emergency=False, additional_notes=additional_notes,added_by=current_user.first_name, user_id=current_user.id)
            db.session.add(new_patient)
            db.session.commit()
            flash('Patient added!', category='success')
        
        return redirect(url_for('views.home'))
    
    try:
        all_patients = Patient.query.filter(Patient.added_by.ilike(f'%{selected_added_by}%')).all()

        current_app.logger.info(f"All Patients: {all_patients}")
    except SQLAlchemyError as e:
        flash(f'Error fetching patients: {str(e)}', category='error')
        all_patients = []

    return render_template("home.html", user=current_user, all_patients=all_patients, added_by_options=added_by_options, selected_added_by=selected_added_by)



from .emergency_email import send_emergency_notification, is_valid_email

@views.route('/toggle-emergency/<int:patient_id>', methods=['POST'])
@login_required
def toggle_emergency(patient_id):
    patient = Patient.query.get(patient_id)
    if patient:
        if patient.user_id == current_user.id:
            patient.is_emergency = not patient.is_emergency
            db.session.commit()

            if patient.is_emergency == True:
                if is_valid_email(patient.contact)==True:
                    send_emergency_notification(patient)
                else:
                    flash('Patient marked as an emergency but can\'t send an email to the contact. Mail is not available')

        else:
            flash('You cannot toggle emergency status for a patient you haven\'t added!', category='error')

    return redirect(url_for('views.home'))


@views.route('/emergencies')
@login_required
def emergencies():
    emergency_patients = Patient.query.filter_by(is_emergency=True).all()
    return render_template("emergencies.html", user=current_user, emergency_patients=emergency_patients)




@views.route('/delete-patient', methods=['POST'])
def delete_patient():
    patient_data = json.loads(request.data)
    patient_id = patient_data['patientId']
    patient = Patient.query.get(patient_id)
    if patient:
        if patient.user_id == current_user.id:
            db.session.delete(patient)
            db.session.commit()
        else:   
            flash('You cannot delete a patient if you haven\'t added them!', category = 'error')  
    return jsonify({})

Project Flask 2024/website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />

    <title>{% block title %}Home{% endblock %}</title>

    <style>
        body {
            background-color: #f8f9fa;
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
        }

        nav.navbar {
            background-color: #343a40;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        nav.navbar a.nav-item {
            color: #fff;
            margin: 0 15px;
            font-size: 1.2em;
            text-decoration: none;
        }

        .container {
            margin-top: 50px;
        }

        .alert {
            margin-top: 20px;
            border-radius: 15px;
            position: relative;
        }

        .alert button.close {
            position: absolute;
            top: 10px;
            right: 10px;
            color: #fff;
            font-size: 1.2em;
            cursor: pointer;
        }

        .alert-danger {
            background-color: #dc3545;
            color: #fff;
            border: none;
        }

        .alert-success {
            background-color: #28a745;
            color: #fff;
            border: none;
        }

            {
            % block customStyles %
        }

        /* Add your custom styles here */
            {
            % endblock %
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                <a class="nav-item nav-link" id="emergencies" href="/emergencies">Emergencies</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    {% block javascript %}
    <script type="text/javascript">
        function deletePatient(patientId) {
            fetch('/delete-patient', {
                method: 'POST',
                body: JSON.stringify({ patientId: patientId }),
            }).then((_res) => {
                window.location.href = "/";
            });
        }
    </script>
    {% endblock %}
</body>

</html>

Project Flask 2024/website/templates/emergencies.html
{% extends "base.html" %}
{% block title %}Emergencies{% endblock %}
{% block content %}
<style>
    body {
        background-color: #1a1a1a;
        color: #fff;
        font-family: 'Montserrat', sans-serif;
    }

    .container {
        margin-top: 50px;
    }

    .list-group-item {
        background-color: #2d2d2d;
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 15px;
        margin-bottom: 20px;
        padding: 20px;
        position: relative;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        transition: background-color 0.3s ease;
    }

    .list-group-item strong {
        color: #55acee;
    }

    .list-group-item:hover {
        background-color: #3d3d3d;
    }

    h2 {
        color: #fff;
        font-size: 2em;
        margin-bottom: 0;
    }
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h2 class="mb-0 text-center">Emergency Patients</h2>
            <ul class="list-group list-group-flash" id="emergency-patients">
                {% for patient in emergency_patients %}
                <li class="list-group-item">
                    <strong>Name:</strong> {{ patient.patient_name }}<br>
                    <strong>Allergy:</strong> {{ patient.allergy }}<br>
                    <strong>Contact:</strong> {{ patient.contact }}<br>
                    <strong>Meds:</strong> {{ patient.meds }}<br>
                    <strong>Added by:</strong> {{ patient.added_by }}<br>
                    <strong>Additional Notes:</strong> {{ patient.additional_notes }}<br>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

Project Flask 2024/website/templates/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
<style>
    body {
        background: #1a1a1a;
        font-family: 'Montserrat', sans-serif;
        color: #fff;
    }

    .container {
        margin-top: 50px;
    }

    .card {
        border: none;
        border-radius: 15px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        background-color: #2d2d2d;
        overflow: hidden;
    }

    .card-header {
        background: #ff6f61;
        color: #fff;
        border-radius: 15px 15px 0 0;
        padding: 20px;
        text-align: center;
        font-size: 2em;
    }

    .alert-info {
        background: #55acee;
        color: #fff;
        border: none;
        border-radius: 10px;
        padding: 15px;
        margin-bottom: 20px;
    }

    #patients {
        margin-top: 20px;
        list-style: none;
        padding: 0;
    }

    li.list-group-item {
        background-color: #2d2d2d;
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 15px;
        margin-bottom: 20px;
        padding: 20px;
        position: relative;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        transition: background-color 0.3s ease;
    }

    li.list-group-item:hover {
        background-color: #3d3d3d;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-control {
        background-color: #2d2d2d;
        color: #fff;
        border: 1px solid #555;
        border-radius: 5px;
    }

    .input-group-append button {
        background-color: #555;
        color: #fff;
        border: 1px solid #555;
        border-radius: 5px;
    }

    .input-group-append button:hover {
        background-color: #777;
        color: #fff;
    }

    .close {
        position: absolute;
        top: 10px;
        right: 10px;
        color: #ff6f61;
        font-size: 1.5em;
        cursor: pointer;
    }

    .close:hover {
        color: #ff3d3d;
    }

    .btn-primary {
        background: #55acee;
        border: none;
        border-radius: 25px;
        padding: 15px 25px;
        font-size: 1.8em;
        transition: background 0.3s ease;
    }

    .btn-primary:hover {
        background: #2795e9;
    }

    .btn-warning {
        background: #ffc107;
        color: #212529;
        border: none;
        border-radius: 5px;
        padding: 5px 10px;
        font-size: 1em;
        cursor: pointer;
        transition: background 0.3s ease;
    }

    .btn-warning:hover {
        background: #ffca2c;
    }

    .btn-emergency {
        background: #dc3545;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 5px 10px;
        font-size: 1em;
        cursor: pointer;
        transition: background 0.3s ease;
    }

    .btn-emergency:hover {
        background: #c82333;
    }

    .btn-add-patient {
        background: #343a40;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 10px 15px;
        font-size: 1.2em;
        cursor: pointer;
        transition: background 0.3s ease;
    }

    .btn-add-patient:hover {
        background: #23272b;
    }
</style>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h2 class="mb-0 text-center">Patients</h2>
                </div>
                <div class="card-body">
                    <div class="alert alert-info" role="alert">
                        Logged in as: {{ user.first_name }} ({{ user.email }})
                        <a href="{{ url_for('auth.logout') }}" class="btn btn-danger btn-sm float-right">Logout</a>
                    </div>
                    <form method="GET" class="mb-3">
                        <div class="input-group">
                            <select class="form-control" name="selected_added_by">
                                <option value="" selected disabled>Select Added By</option>
                                {% for option in added_by_options %}
                                <option value="{{ option }}" {% if option==selected_added_by %}selected{% endif %}>{{
                                    option }}</option>
                                {% endfor %}
                            </select>
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Filter</button>
                            </div>
                        </div>
                    </form>
                    <ul class="list-group list-group-flash" id="patients">
                        {% for patient in all_patients %}
                        <li id="patient-{{ patient.id }}" class="list-group-item">
                            <strong>Name:</strong> {{ patient.patient_name }}<br>
                            <strong>Allergy:</strong> {{ patient.allergy }}<br>
                            <strong>Contact:</strong> {{ patient.contact }}<br>
                            <strong>Meds:</strong> {{ patient.meds }}<br>
                            <strong>Date:</strong> {{ patient.date }}<br>
                            <strong>Added by:</strong> {{ patient.added_by }}<br>
                            <strong>Emergency:</strong> {% if patient.is_emergency == 1 %}Yes{% else %}No{% endif %}<br>
                            <strong>Additional Notes:</strong> {{ patient.additional_notes }}<br>
                            <form method="POST" action="{{ url_for('views.toggle_emergency', patient_id=patient.id) }}"
                                class="mt-2">
                                <button type="submit" class="btn btn-emergency">
                                    {% if patient.is_emergency %}Remove from Emergencies{% else %}Mark as Emergency{%
                                    endif %}
                                </button>
                            </form>

                            <button type="button" class="close" onClick="deletePatient({{ patient.id }})">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </li>
                        {% endfor %}
                    </ul>
                    <form method="POST" class="mt-3">
                        <div class="form-group">
                            <label for="patient_name">Patient Name:</label>
                            <input type="text" name="patient_name" id="patient_name" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="allergy">Allergy:</label>
                            <input type="text" name="allergy" id="allergy" class="form-control" placeholder="Optional">
                        </div>

                        <div class="form-group">
                            <label for="contact">Contact:</label>
                            <input type="text" name="contact" id="contact" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="meds">Meds:</label>
                            <input type="text" name="meds" id="meds" class="form-control" placeholder="Optional">
                        </div>

                        <div class="form-group">
                            <label for="allergy">Additional Notes:</label>
                            <input type="text" name="additional_notes" id="additional_notes" class="form-control"
                                placeholder="Optional">
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-add-patient">Add Patient</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function toggleEmergency(patientId) {
        fetch(`/toggle-emergency/${patientId}`, {
            method: 'POST',
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                const patientElement = document.getElementById(`patient-${patientId}`);
                if (patientElement) {
                    patientElement.classList.toggle('emergency', data.is_emergency);
                }
                // Use JavaScript to navigate back to the home page
                window.location.href = '{{ url_for("views.home") }}';
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }
</script>

{% endblock %}

Project Flask 2024/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
  body {
    background-color: #343a40;
    color: #fff;
    font-family: 'Arial', sans-serif;
  }

  form {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    background-color: #2d2d2d;
  }

  h3 {
    color: #007bff;
    text-align: center;
    margin-bottom: 30px;
  }

  label {
    color: #ced4da;
  }

  .form-control {
    border: 1px solid #495057;
    border-radius: 5px;
    background-color: #495057;
    color: #fff;
  }

  .form-group {
    margin-bottom: 20px;
  }

  button.btn-primary {
    background-color: #007bff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    font-size: 1.2em;
    color: #fff;
    cursor: pointer;
    transition: background 0.3s ease;
  }

  button.btn-primary:hover {
    background-color: #0056b3;
  }
</style>

<form method="POST">
  <h3>Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Project Flask 2024/website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<style>
  body {
    background-color: #343a40;
    color: #fff;
    font-family: 'Arial', sans-serif;
  }

  form {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    background-color: #2d2d2d;
  }

  h3 {
    color: #28a745;
    text-align: center;
    margin-bottom: 30px;
  }

  label {
    color: #007bff;
  }

  .form-control {
    border: 1px solid #495057;
    border-radius: 5px;
    background-color: #495057;
    color: #fff;
  }

  .form-group {
    margin-bottom: 20px;
  }

  button.btn-primary {
    background-color: #007bff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    font-size: 1.2em;
    color: #fff;
    cursor: pointer;
    transition: background 0.3s ease;
  }

  button.btn-primary:hover {
    background-color: #0056b3;
  }
</style>

<form method="POST">
  <h3>Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name" />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password" />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}